### ISSUE TITLE
build error: ‘class thpp::Storage<float>’ has no member named ‘getIOBuf’

### ISSUE THREAD

**Issue by orbitbus** [facebook/thpp#25]
A duplicate of this has been closed a few days ago by the author but there is no solution that works so I'm 'reopening' it here.

thpp (master or v1) fail to compile with the above error, whether or not NO_FOLLY and NO_THRIFT are specified. Please give a solution without folly as that seems a lot simpler than reverting to why folly doesn't properly install.
System: latest 14.04 LTS Ubuntu, with torch and nothing else installed

**Comment by orbitbus** [comment]
Seems fb open source is DIY. 
THPP master does NOT work with Ubuntu 14.04. Neither does v1 because then you need special revisions for fbthrift and folly. Read the one line install script for fblualib on which revision it downloads for 14.04. 
Finally, the google link for gtest1.0.7.zip has changed, so the old build.sh for thpp v1 also fails - you need to change the url to the one from the master build.sh. Then it works.
